### ISSUE TITLE
Davis' Resume Homework

### ISSUE THREAD

**Issue by Mahartney** [ga-dc/curriculum#313]
Comfort: 4/5
Completeness 5/5; I had a little confusion with the instructions so I'm not 100% I've provided everything in as you're expecting them.

My Repo: https://github.com/Mahartney/Mahartney.github.io
My Resume: http://mahartney.github.io/
My Forked Curriculum: https://github.com/Mahartney/curriculum

**Comment by jshawl** [comment]
:+1: Looks good! For future assignments, I will leave line comments on a pull request. Here is feedback on your resume code:

There are two files: DavisResumeWorking.html and index.html. Instead of copying files to keep track of versions, use git. Commit early and often - we'll take a look at how to revert changes this week
