### ISSUE TITLE
Javascript-dataTypes-Conditionals-Loops: Delta's Scope of class  

### ISSUE THREAD

**Issue by nolds9** [ga-dc/curriculum#331]
- Brief intro to developer tools, and why we use chrome, etc.
- Possibly work-in more you do's in the console
- Make sure we are clearing the console - hard to see in back of the class
- Demo console.log
- Go more in depth into variables or maybe do not get into global vs local scope - defer to upcoming lessons

**Comment by andrewsunglaekim** [comment]
definitely a great call, introducing scope this early probably just confused them a bit.

**Comment by andrewsunglaekim** [comment]
Action items: took some personal notes since there not really much to change lesson plan wise based on deltas. That being said included `console.log` and a blurb about dev tools in most recent push. Cutting out the exercises as a temporary solution since I didn't have time for them and place exercises cut at the bottom of lesson plan for instructor flexibilty
